# Generated by Django 4.2.7 on 2024-01-28 14:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_faourite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faourite',
            new_name='Favourite',
        ),
    ]
